name: Enviar Regras PF

on:
  workflow_dispatch:

jobs:
  enviar:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar requests
        run: pip install requests

      - name: Enviar regras
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: python enviar_regras.py
